### ISSUE TITLE
Palemoon Compatibility?

### ISSUE THREAD

**Issue by dtoxic47** [RobertZenz/ThinBars#12]
is it possible?

**Comment by RobertZenz** [comment]
I was looking into it, but for some reason ThinBars does absolutely nothing when started in Palemoon. Either the current master is completely broken or there is something different going on. Anyway, that is why I didn't release it together with the other two addons.

But yes, that is the plan.

**Comment by dtoxic47** [comment]
ohh ok, just though id ask the question here

**Comment by RobertZenz** [comment]
The v1.2 release adds support, with the caveat that quite a few of the options are doing nothing (for various reasons). I'm not sure when I'll work on it again, so I'd rather release it like this than not at all. I've already contacted the Palemoon staff if I can add it like that to the AddOn site, we'll see.
